version: "3.12"
services:
  db:
    image: postgres:15
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5432:5432"

  fastapi:
    build:
      context: .
    container_name: fastapi_app
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: >
      sh -c "./wait_for_it.sh db:5432 -- sh -c 'cd backend/db && alembic upgrade head && cd .. && cd .. && uvicorn backend.api.main:app --host 0.0.0.0 --port 8000'"