"""added line table to env

Revision ID: 18cbb427c220
Revises: f6a5adbe3f26
Create Date: 2025-02-02 14:46:18.231870

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = '18cbb427c220'
down_revision = 'f6a5adbe3f26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
