"""refactored hour archive model

Revision ID: 2e734ba977f6
Revises: a6f470fc04cf
Create Date: 2025-03-22 13:03:49.498266

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = '2e734ba977f6'
down_revision = 'a6f470fc04cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hourly_archive', 'volume',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('hourly_archive', 'w_volume_dp',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('hourly_archive', 'pressure',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('hourly_archive', 'temperature',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('hourly_archive', 'density',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hourly_archive', 'density',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('hourly_archive', 'temperature',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('hourly_archive', 'pressure',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('hourly_archive', 'w_volume_dp',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('hourly_archive', 'volume',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    # ### end Alembic commands ###
