"""Initial migration

Revision ID: 41e15a2b268e
Revises: 
Create Date: 2025-01-05 19:58:17.443940

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = '41e15a2b268e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gas_vol_calc_type',
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('type_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type_name')
    )
    op.create_table('lumg',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('edit_type',
    sa.Column('edit_type_id', sa.Integer(), nullable=False),
    sa.Column('edit_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gas_volume_calc_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gas_volume_calc_type_id'], ['gas_vol_calc_type.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('edit_type_id', 'gas_volume_calc_type_id', name='edit_type_id_constraint')
    )
    op.create_table('gas_volume_calc',
    sa.Column('address', sa.Integer(), nullable=False),
    sa.Column('line', sa.Integer(), nullable=False),
    sa.Column('meter', sa.Boolean(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('c_time', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lumg_id', sa.Integer(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lumg_id'], ['lumg.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['type_id'], ['gas_vol_calc_type.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lumg_id', 'address', name='lumg_adress_constraint'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sys_type',
    sa.Column('sys_type_id', sa.Integer(), nullable=False),
    sa.Column('sys_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gas_volume_calc_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gas_volume_calc_type_id'], ['gas_vol_calc_type.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sys_type_id', 'gas_volume_calc_type_id', name='sys_type_id_constraint')
    )
    op.create_table('daily_archive',
    sa.Column('line', sa.Integer(), nullable=False),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('volume', sa.Numeric(scale=3), nullable=False),
    sa.Column('w_volume_dp', sa.Numeric(scale=3), nullable=False),
    sa.Column('pressure', sa.Numeric(scale=3), nullable=False),
    sa.Column('temperature', sa.Numeric(scale=3), nullable=False),
    sa.Column('density', sa.Numeric(scale=3), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gas_vol_calc_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gas_vol_calc_id'], ['gas_volume_calc.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gas_vol_calc_id', 'line', 'period', name='calc_id_line_period_constraint')
    )
    op.create_index(op.f('ix_daily_archive_period'), 'daily_archive', ['period'], unique=False)
    op.create_table('edit_archive',
    sa.Column('period', sa.DateTime(), nullable=False),
    sa.Column('line', sa.Integer(), nullable=False),
    sa.Column('old_value', sa.Integer(), nullable=False),
    sa.Column('new_value', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('edit_id', sa.Integer(), nullable=True),
    sa.Column('gas_vol_calc_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['edit_id'], ['edit_type.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gas_vol_calc_id'], ['gas_volume_calc.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period', 'edit_id', 'gas_vol_calc_id', name='edit_id_period_constraint')
    )
    op.create_index(op.f('ix_edit_archive_period'), 'edit_archive', ['period'], unique=False)
    op.create_table('hourly_archive',
    sa.Column('line', sa.Integer(), nullable=False),
    sa.Column('period', sa.DateTime(), nullable=False),
    sa.Column('volume', sa.Numeric(scale=3), nullable=False),
    sa.Column('w_volume_dp', sa.Numeric(scale=3), nullable=False),
    sa.Column('pressure', sa.Numeric(scale=3), nullable=False),
    sa.Column('temperature', sa.Numeric(scale=3), nullable=False),
    sa.Column('density', sa.Numeric(scale=3), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gas_vol_calc_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gas_vol_calc_id'], ['gas_volume_calc.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gas_vol_calc_id', 'line', 'period', name='calc_id_line_period_constraint')
    )
    op.create_index(op.f('ix_hourly_archive_period'), 'hourly_archive', ['period'], unique=False)
    op.create_table('sys_archive',
    sa.Column('period', sa.DateTime(), nullable=False),
    sa.Column('line', sa.Integer(), nullable=False),
    sa.Column('standard_volume', sa.Numeric(precision=20, scale=3), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sys_type_id', sa.Integer(), nullable=False),
    sa.Column('gas_vol_calc_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gas_vol_calc_id'], ['gas_volume_calc.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sys_type_id'], ['sys_type.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period', 'sys_type_id', 'gas_vol_calc_id', name='line_period_constraint')
    )
    op.create_index(op.f('ix_sys_archive_period'), 'sys_archive', ['period'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sys_archive_period'), table_name='sys_archive')
    op.drop_table('sys_archive')
    op.drop_index(op.f('ix_hourly_archive_period'), table_name='hourly_archive')
    op.drop_table('hourly_archive')
    op.drop_index(op.f('ix_edit_archive_period'), table_name='edit_archive')
    op.drop_table('edit_archive')
    op.drop_index(op.f('ix_daily_archive_period'), table_name='daily_archive')
    op.drop_table('daily_archive')
    op.drop_table('sys_type')
    op.drop_table('gas_volume_calc')
    op.drop_table('edit_type')
    op.drop_table('lumg')
    op.drop_table('gas_vol_calc_type')
    # ### end Alembic commands ###
