"""added params table

Revision ID: 52d8a639326d
Revises: c3d568b44428
Create Date: 2025-03-22 12:12:11.583635

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = '52d8a639326d'
down_revision = 'c3d568b44428'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('params',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('period', sa.DateTime(), nullable=False),
    sa.Column('density', sa.Float(), nullable=False),
    sa.Column('co2', sa.Float(), nullable=False),
    sa.Column('n2', sa.Float(), nullable=False),
    sa.Column('D20', sa.Float(), nullable=False),
    sa.Column('d20', sa.Float(), nullable=False),
    sa.Column('cutoff', sa.Float(), nullable=False),
    sa.Column('roughness', sa.Float(), nullable=False),
    sa.Column('max_dp', sa.Float(), nullable=False),
    sa.Column('min_dp', sa.Float(), nullable=False),
    sa.Column('A0su', sa.Float(), nullable=False),
    sa.Column('A1su', sa.Float(), nullable=False),
    sa.Column('A2su', sa.Float(), nullable=False),
    sa.Column('A0pipe', sa.Float(), nullable=False),
    sa.Column('A1pipe', sa.Float(), nullable=False),
    sa.Column('A2pipe', sa.Float(), nullable=False),
    sa.Column('radius', sa.Float(), nullable=False),
    sa.Column('su_year', sa.Float(), nullable=False),
    sa.Column('max_p', sa.Float(), nullable=False),
    sa.Column('min_p', sa.Float(), nullable=False),
    sa.Column('max_t', sa.Float(), nullable=False),
    sa.Column('min_t', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['line_id'], ['gas_volume_line.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('line_id', 'period', name='param_line_period_constraint')
    )
    op.create_index(op.f('ix_params_line_id'), 'params', ['line_id'], unique=False)
    op.create_index(op.f('ix_params_period'), 'params', ['period'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_params_period'), table_name='params')
    op.drop_index(op.f('ix_params_line_id'), table_name='params')
    op.drop_table('params')
    # ### end Alembic commands ###
