"""change edit models and logic

Revision ID: 86afa1124c1c
Revises: 089898b167d1
Create Date: 2025-03-20 18:05:36.993977

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = '86afa1124c1c'
down_revision = '089898b167d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('edit_archive', sa.Column('edit_type_id', sa.Integer(), nullable=False))
    op.drop_constraint('edit_all_constraint', 'edit_archive', type_='unique')
    op.create_unique_constraint('edit_all_constraint', 'edit_archive', ['period', 'edit_type_id', 'line_id', 'new_value', 'old_value'])
    op.drop_constraint('edit_archive_edit_id_fkey', 'edit_archive', type_='foreignkey')
    op.drop_column('edit_archive', 'edit_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('edit_archive', sa.Column('edit_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('edit_archive_edit_id_fkey', 'edit_archive', 'edit_type', ['edit_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('edit_all_constraint', 'edit_archive', type_='unique')
    op.create_unique_constraint('edit_all_constraint', 'edit_archive', ['period', 'edit_id', 'line_id', 'new_value', 'old_value'])
    op.drop_column('edit_archive', 'edit_type_id')
    # ### end Alembic commands ###
