"""line model

Revision ID: 8eaac00e05f7
Revises: 7c908a122511
Create Date: 2025-02-02 10:41:57.875426

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = '8eaac00e05f7'
down_revision = '7c908a122511'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
