"""updated sys edit types models

Revision ID: c3d568b44428
Revises: f3ca6152901a
Create Date: 2025-03-20 20:27:24.284509

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = 'c3d568b44428'
down_revision = 'f3ca6152901a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('edit_type', 'gas_volume_calc_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('edit_type_gas_volume_calc_type_id_fkey', 'edit_type', type_='foreignkey')
    op.alter_column('sys_type', 'gas_volume_calc_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('sys_type_gas_volume_calc_type_id_fkey', 'sys_type', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('sys_type_gas_volume_calc_type_id_fkey', 'sys_type', 'gas_vol_calc_type', ['gas_volume_calc_type_id'], ['id'], ondelete='CASCADE')
    op.alter_column('sys_type', 'gas_volume_calc_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key('edit_type_gas_volume_calc_type_id_fkey', 'edit_type', 'gas_vol_calc_type', ['gas_volume_calc_type_id'], ['id'], ondelete='CASCADE')
    op.alter_column('edit_type', 'gas_volume_calc_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
