"""fix param model

Revision ID: d3579290ea96
Revises: 2e734ba977f6
Create Date: 2025-03-22 21:27:53.152762

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = 'd3579290ea96'
down_revision = '2e734ba977f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('param_line_period_constraint', 'params', type_='unique')
    op.create_unique_constraint('param_all_constraint', 'params', ['density', 'co2', 'n2', 'D20', 'd20', 'cutoff', 'roughness', 'max_dp', 'min_dp', 'A0su', 'A1su', 'A2su', 'A0pipe', 'A1pipe', 'A2pipe', 'radius', 'su_year', 'max_p', 'min_p', 'max_t', 'min_t', 'line_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('param_all_constraint', 'params', type_='unique')
    op.create_unique_constraint('param_line_period_constraint', 'params', ['line_id', 'period'])
    # ### end Alembic commands ###
