"""change sys models and logic

Revision ID: f3ca6152901a
Revises: 86afa1124c1c
Create Date: 2025-03-20 18:23:04.651060

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = 'f3ca6152901a'
down_revision = '86afa1124c1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sys_archive', sa.Column('volume', sa.Numeric(precision=20, scale=3), nullable=False))
    op.drop_constraint('sys_all_constraint', 'sys_archive', type_='unique')
    op.create_unique_constraint('sys_all_constraint', 'sys_archive', ['period', 'sys_type_id', 'line_id', 'volume'])
    op.drop_constraint('sys_archive_sys_type_id_fkey', 'sys_archive', type_='foreignkey')
    op.drop_column('sys_archive', 'standard_volume')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sys_archive', sa.Column('standard_volume', sa.NUMERIC(precision=20, scale=3), autoincrement=False, nullable=False))
    op.create_foreign_key('sys_archive_sys_type_id_fkey', 'sys_archive', 'sys_type', ['sys_type_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('sys_all_constraint', 'sys_archive', type_='unique')
    op.create_unique_constraint('sys_all_constraint', 'sys_archive', ['period', 'sys_type_id', 'line_id', 'standard_volume'])
    op.drop_column('sys_archive', 'volume')
    # ### end Alembic commands ###
