"""line model refactorng

Revision ID: f6a5adbe3f26
Revises: 8eaac00e05f7
Create Date: 2025-02-02 14:26:30.408188

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = 'f6a5adbe3f26'
down_revision = '8eaac00e05f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
